// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using AccountTest;

namespace Addressbook
{

    [TestFixture]
    public class ContactTest : TestBase
    { 
        [Test]
        public void Contact()
        {
            PersonInfo personInfo = new PersonInfo("Diman");
            personInfo.Address = "Limbo";
            personInfo.LastName = "Dimansky";
            personInfo.Email = "nownownow@mail.ru";
            app.Navigator.GoToNewContactPage();
            app.ContactHelper.Create(personInfo);
            app.LogoutHelper.LogOut();

        }
    }
}
