// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Addressbook
{

    [TestFixture]
    public class CreateGroupTest : TestBaseAuth
    {
        [Test]
        public void GroupTest()
        {
            GroupData groupData = new GroupData("testgroup");
            groupData.Footer = "testgroup";
            groupData.Header = "testgroup";
            app.GroupHelper.Create(groupData);
            app.AuthUser.Logout();
        }
    }
}